name: "Job"

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  analyze:
    name: Test
    runs-on: [self-hosted, Windows]
    permissions:
      # required for all workflows
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        allow-unsafe-pr-checkout: true
        
    - name: 'Install node'
      uses: actions/setup-node@v6
      with:
        node-version: 24
        package-manager-cache: false # Disable automatic npm caching if not required
