name: "Job"

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  analyze:
    name: Test
    runs-on: [self-hosted, Linux]
    permissions:
      # required for all workflows
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        allow-unsafe-pr-checkout: true
        
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v5
