name: "Job"

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  analyze:
    name: Test
    runs-on: [self-hosted, Windows]
    permissions:
      # required for all workflows
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        allow-unsafe-pr-checkout: true
        
    - name: Run Claude
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
